import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/landing/Header";

const fonts = Inter({ subsets: ["cyrillic", "latin"] });

export const metadata: Metadata = {
  title: "Forest Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fonts.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
